#############################################################################
# Makefile for building: pes-lib.app/Contents/MacOS/pes-lib
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  libpes.pro
# Template: app
# Command: /Users/joshvarga/Qt/5.4/clang_64/bin/qmake -o Makefile libpes.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = 
CFLAGS        = -pipe -std=c89 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -IPesLib -I../../Qt/5.4/clang_64/mkspecs/macx-clang
QMAKE         = /Users/joshvarga/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pes-lib1.0.0
DISTDIR = /Users/joshvarga/Documents/PesLib/.obj/pes-lib1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS)  
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = PesLib/CMExeEmb.c \
		PesLib/CTTFLetter.c \
		PesLib/PesLib.c \
		PesLib/affine-transform.c \
		PesLib/block-geometry.c \
		PesLib/helpers-binary.c \
		PesLib/pes-circ.c \
		PesLib/pes-dtext.c \
		PesLib/pes-group-object.c \
		PesLib/pes-header.c \
		PesLib/pes-letter.c \
		PesLib/pes-line.c \
		PesLib/pes-motif-data.c \
		PesLib/pes-motif.c \
		PesLib/pes-mtext.c \
		PesLib/pes-ntext.c \
		PesLib/pes-one.c \
		PesLib/pes-point.c \
		PesLib/pes-punch.c \
		PesLib/pes-rect.c \
		PesLib/pes-satin-stitch.c \
		PesLib/pes-sew-fig-seg.c \
		PesLib/pes-sew-seg.c \
		PesLib/pes-special-shape.c \
		PesLib/pes-stamp-description.c \
		PesLib/pes-stitch-block.c \
		PesLib/pes-thread.c \
		PesLib/pes-tile-line.c \
		PesLib/point.c \
		PesLib/short-array.c \
		PesLib/stitch-block-description.c \
		PesLib/pes_pat.c 
OBJECTS       = .obj/CMExeEmb.o \
		.obj/CTTFLetter.o \
		.obj/PesLib.o \
		.obj/affine-transform.o \
		.obj/block-geometry.o \
		.obj/helpers-binary.o \
		.obj/pes-circ.o \
		.obj/pes-dtext.o \
		.obj/pes-group-object.o \
		.obj/pes-header.o \
		.obj/pes-letter.o \
		.obj/pes-line.o \
		.obj/pes-motif-data.o \
		.obj/pes-motif.o \
		.obj/pes-mtext.o \
		.obj/pes-ntext.o \
		.obj/pes-one.o \
		.obj/pes-point.o \
		.obj/pes-punch.o \
		.obj/pes-rect.o \
		.obj/pes-satin-stitch.o \
		.obj/pes-sew-fig-seg.o \
		.obj/pes-sew-seg.o \
		.obj/pes-special-shape.o \
		.obj/pes-stamp-description.o \
		.obj/pes-stitch-block.o \
		.obj/pes-thread.o \
		.obj/pes-tile-line.o \
		.obj/point.o \
		.obj/short-array.o \
		.obj/stitch-block-description.o \
		.obj/pes_pat.o
DIST          = ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		libpes.pro PesLib/CMExeEmb.h \
		PesLib/CTTFLetter.h \
		PesLib/PesStitchBlock.h \
		PesLib/affine-transform.h \
		PesLib/block-geometry.h \
		PesLib/helpers-binary.h \
		PesLib/pes-circ.h \
		PesLib/pes-dtext.h \
		PesLib/pes-group-object.h \
		PesLib/pes-header.h \
		PesLib/pes-letter.h \
		PesLib/pes-line.h \
		PesLib/pes-motif-data.h \
		PesLib/pes-motif.h \
		PesLib/pes-mtext.h \
		PesLib/pes-ntext.h \
		PesLib/pes-one.h \
		PesLib/pes-point.h \
		PesLib/pes-punch.h \
		PesLib/pes-rect.h \
		PesLib/pes-satin-stitch.h \
		PesLib/pes-sew-fig-seg.h \
		PesLib/pes-sew-seg.h \
		PesLib/pes-special-shape.h \
		PesLib/pes-stamp-description.h \
		PesLib/pes-stext.h \
		PesLib/pes-thread.h \
		PesLib/point.h \
		PesLib/short-array.h \
		PesLib/stitch-block-description.h \
		PesLib/tile-line.h \
		PesLib/pes_pat.h PesLib/CMExeEmb.c \
		PesLib/CTTFLetter.c \
		PesLib/PesLib.c \
		PesLib/affine-transform.c \
		PesLib/block-geometry.c \
		PesLib/helpers-binary.c \
		PesLib/pes-circ.c \
		PesLib/pes-dtext.c \
		PesLib/pes-group-object.c \
		PesLib/pes-header.c \
		PesLib/pes-letter.c \
		PesLib/pes-line.c \
		PesLib/pes-motif-data.c \
		PesLib/pes-motif.c \
		PesLib/pes-mtext.c \
		PesLib/pes-ntext.c \
		PesLib/pes-one.c \
		PesLib/pes-point.c \
		PesLib/pes-punch.c \
		PesLib/pes-rect.c \
		PesLib/pes-satin-stitch.c \
		PesLib/pes-sew-fig-seg.c \
		PesLib/pes-sew-seg.c \
		PesLib/pes-special-shape.c \
		PesLib/pes-stamp-description.c \
		PesLib/pes-stitch-block.c \
		PesLib/pes-thread.c \
		PesLib/pes-tile-line.c \
		PesLib/point.c \
		PesLib/short-array.c \
		PesLib/stitch-block-description.c \
		PesLib/pes_pat.c
QMAKE_TARGET  = pes-lib
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = pes-lib.app/Contents/MacOS/pes-lib

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d pes-lib.app/Contents/MacOS/ || mkdir -p pes-lib.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: libpes.pro ../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		libpes.pro
	$(QMAKE) -o Makefile libpes.pro
../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
libpes.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile libpes.pro

qmake_all: FORCE

pes-lib.app/Contents/PkgInfo: 
	@test -d pes-lib.app/Contents || mkdir -p pes-lib.app/Contents
	@$(DEL_FILE) pes-lib.app/Contents/PkgInfo
	@echo "APPL????" >pes-lib.app/Contents/PkgInfo
pes-lib.app/Contents/Resources/empty.lproj: 
	@test -d pes-lib.app/Contents/Resources || mkdir -p pes-lib.app/Contents/Resources
	@touch pes-lib.app/Contents/Resources/empty.lproj
	
pes-lib.app/Contents/Info.plist: 
	@test -d pes-lib.app/Contents || mkdir -p pes-lib.app/Contents
	@$(DEL_FILE) pes-lib.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.pes-lib,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,pes-lib,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >pes-lib.app/Contents/Info.plist

all: Makefile \
		pes-lib.app/Contents/PkgInfo \
		pes-lib.app/Contents/Resources/empty.lproj \
		pes-lib.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r pes-lib.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

.obj/CMExeEmb.o: PesLib/CMExeEmb.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/CMExeEmb.o PesLib/CMExeEmb.c

.obj/CTTFLetter.o: PesLib/CTTFLetter.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/CTTFLetter.o PesLib/CTTFLetter.c

.obj/PesLib.o: PesLib/PesLib.c PesLib/pes-circ.h \
		PesLib/stitch-block-description.h \
		PesLib/affine-transform.h \
		PesLib/block-geometry.h \
		PesLib/pes-motif.h \
		PesLib/pes-header.h \
		PesLib/short-array.h \
		PesLib/pes-motif-data.h \
		PesLib/point.h \
		PesLib/pes_pat.h \
		PesLib/tile-line.h \
		PesLib/pes-thread.h \
		PesLib/pes-line.h \
		PesLib/pes-point.h \
		PesLib/pes-ntext.h \
		PesLib/pes-letter.h \
		PesLib/pes-one.h \
		PesLib/pes-punch.h \
		PesLib/pes-rect.h \
		PesLib/pes-special-shape.h \
		PesLib/helpers-binary.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/PesLib.o PesLib/PesLib.c

.obj/affine-transform.o: PesLib/affine-transform.c PesLib/affine-transform.h \
		PesLib/helpers-binary.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/affine-transform.o PesLib/affine-transform.c

.obj/block-geometry.o: PesLib/block-geometry.c PesLib/helpers-binary.h \
		PesLib/block-geometry.h \
		PesLib/affine-transform.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/block-geometry.o PesLib/block-geometry.c

.obj/helpers-binary.o: PesLib/helpers-binary.c PesLib/helpers-binary.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/helpers-binary.o PesLib/helpers-binary.c

.obj/pes-circ.o: PesLib/pes-circ.c PesLib/helpers-binary.h \
		PesLib/pes-circ.h \
		PesLib/stitch-block-description.h \
		PesLib/affine-transform.h \
		PesLib/block-geometry.h \
		PesLib/pes-motif.h \
		PesLib/pes-point.h \
		PesLib/point.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-circ.o PesLib/pes-circ.c

.obj/pes-dtext.o: PesLib/pes-dtext.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-dtext.o PesLib/pes-dtext.c

.obj/pes-group-object.o: PesLib/pes-group-object.c PesLib/helpers-binary.h \
		PesLib/pes-group-object.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-group-object.o PesLib/pes-group-object.c

.obj/pes-header.o: PesLib/pes-header.c PesLib/affine-transform.h \
		PesLib/helpers-binary.h \
		PesLib/pes-header.h \
		PesLib/short-array.h \
		PesLib/pes-motif.h \
		PesLib/pes-motif-data.h \
		PesLib/point.h \
		PesLib/pes_pat.h \
		PesLib/tile-line.h \
		PesLib/pes-thread.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-header.o PesLib/pes-header.c

.obj/pes-letter.o: PesLib/pes-letter.c PesLib/helpers-binary.h \
		PesLib/pes-letter.h \
		PesLib/stitch-block-description.h \
		PesLib/affine-transform.h \
		PesLib/block-geometry.h \
		PesLib/pes-motif.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-letter.o PesLib/pes-letter.c

.obj/pes-line.o: PesLib/pes-line.c PesLib/helpers-binary.h \
		PesLib/pes-line.h \
		PesLib/pes-point.h \
		PesLib/point.h \
		PesLib/stitch-block-description.h \
		PesLib/affine-transform.h \
		PesLib/block-geometry.h \
		PesLib/pes-motif.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-line.o PesLib/pes-line.c

.obj/pes-motif-data.o: PesLib/pes-motif-data.c PesLib/helpers-binary.h \
		PesLib/pes-motif-data.h \
		PesLib/point.h \
		PesLib/tile-line.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-motif-data.o PesLib/pes-motif-data.c

.obj/pes-motif.o: PesLib/pes-motif.c PesLib/helpers-binary.h \
		PesLib/pes-motif.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-motif.o PesLib/pes-motif.c

.obj/pes-mtext.o: PesLib/pes-mtext.c PesLib/block-geometry.h \
		PesLib/affine-transform.h \
		PesLib/helpers-binary.h \
		PesLib/pes-letter.h \
		PesLib/pes-mtext.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-mtext.o PesLib/pes-mtext.c

.obj/pes-ntext.o: PesLib/pes-ntext.c PesLib/block-geometry.h \
		PesLib/affine-transform.h \
		PesLib/helpers-binary.h \
		PesLib/pes-letter.h \
		PesLib/pes-ntext.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-ntext.o PesLib/pes-ntext.c

.obj/pes-one.o: PesLib/pes-one.c PesLib/affine-transform.h \
		PesLib/pes-one.h \
		PesLib/block-geometry.h \
		PesLib/helpers-binary.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-one.o PesLib/pes-one.c

.obj/pes-point.o: PesLib/pes-point.c PesLib/helpers-binary.h \
		PesLib/pes-point.h \
		PesLib/point.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-point.o PesLib/pes-point.c

.obj/pes-punch.o: PesLib/pes-punch.c PesLib/helpers-binary.h \
		PesLib/pes-punch.h \
		PesLib/block-geometry.h \
		PesLib/affine-transform.h \
		PesLib/pes-sew-fig-seg.h \
		PesLib/pes-motif.h \
		PesLib/pes-point.h \
		PesLib/point.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-punch.o PesLib/pes-punch.c

.obj/pes-rect.o: PesLib/pes-rect.c PesLib/helpers-binary.h \
		PesLib/pes-rect.h \
		PesLib/stitch-block-description.h \
		PesLib/affine-transform.h \
		PesLib/block-geometry.h \
		PesLib/pes-motif.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-rect.o PesLib/pes-rect.c

.obj/pes-satin-stitch.o: PesLib/pes-satin-stitch.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-satin-stitch.o PesLib/pes-satin-stitch.c

.obj/pes-sew-fig-seg.o: PesLib/pes-sew-fig-seg.c PesLib/affine-transform.h \
		PesLib/pes-point.h \
		PesLib/point.h \
		PesLib/pes-sew-fig-seg.h \
		PesLib/pes-motif.h \
		PesLib/helpers-binary.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-sew-fig-seg.o PesLib/pes-sew-fig-seg.c

.obj/pes-sew-seg.o: PesLib/pes-sew-seg.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-sew-seg.o PesLib/pes-sew-seg.c

.obj/pes-special-shape.o: PesLib/pes-special-shape.c PesLib/block-geometry.h \
		PesLib/affine-transform.h \
		PesLib/helpers-binary.h \
		PesLib/pes-special-shape.h \
		PesLib/pes-point.h \
		PesLib/point.h \
		PesLib/stitch-block-description.h \
		PesLib/pes-motif.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-special-shape.o PesLib/pes-special-shape.c

.obj/pes-stamp-description.o: PesLib/pes-stamp-description.c PesLib/helpers-binary.h \
		PesLib/pes-stamp-description.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-stamp-description.o PesLib/pes-stamp-description.c

.obj/pes-stitch-block.o: PesLib/pes-stitch-block.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-stitch-block.o PesLib/pes-stitch-block.c

.obj/pes-thread.o: PesLib/pes-thread.c PesLib/helpers-binary.h \
		PesLib/pes-thread.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-thread.o PesLib/pes-thread.c

.obj/pes-tile-line.o: PesLib/pes-tile-line.c PesLib/helpers-binary.h \
		PesLib/tile-line.h \
		PesLib/point.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes-tile-line.o PesLib/pes-tile-line.c

.obj/point.o: PesLib/point.c PesLib/helpers-binary.h \
		PesLib/point.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/point.o PesLib/point.c

.obj/short-array.o: PesLib/short-array.c PesLib/helpers-binary.h \
		PesLib/short-array.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/short-array.o PesLib/short-array.c

.obj/stitch-block-description.o: PesLib/stitch-block-description.c PesLib/helpers-binary.h \
		PesLib/pes-motif.h \
		PesLib/short-array.h \
		PesLib/stitch-block-description.h \
		PesLib/affine-transform.h \
		PesLib/block-geometry.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/stitch-block-description.o PesLib/stitch-block-description.c

.obj/pes_pat.o: PesLib/pes_pat.c PesLib/helpers-binary.h \
		PesLib/pes_pat.h \
		PesLib/tile-line.h \
		PesLib/point.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o .obj/pes_pat.o PesLib/pes_pat.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

